# Cryptocurrency Trading with the World {#Crypto-trading Bot}

#### Keywords {-}

cryptocurrency, trading, investing, bitcoin

## The State of Cryptocurrency.

In the last two months of 2017, the cryptocurrency market went beserk. As families got together for Thanksgiving, the word about Bitcoin's rapid growth got spread around and soon everyone wanted a piece of the action. People began tweeting about cryptocurrencies, new podcasts began to spring up, and even media outlets began to report on the insane growth. These internet currencies began expanding at a newly found rapid rate due to a new factor : _word of mouth_. Word of mouth can be used to see the general consesus of a particular cryptocurrency and then make an informed decision (buy or sell) and thus help students secure enough capital to pay off loans (or buy [Lamborghinis](http://www.businessinsider.com/a-4chan-user-bought-a-200000-lamborghini-using-bitcoin-2013-12)).
[@katz_number_nodate]

## A Plan to Make Money.

#### Overview

In order to utilize the word of mouth idea, we will need to collect a lot of data, not just about coins, but also about what people are saying about certain coins. Fortunately, a lot of this data is widely available online.

#### The Process

In order to ensure that we are getting the best data possible, we have to utilize various APIs to get data. Ideally we'll need data from three sources:

1. Price data
2. Sentiment data
3. News data

We can get price data from several websites; however, there are certain sites that will allow us to get information for a lot of coins at the once. The first and perhaps best site to get information from is [CoinMarketCap](https://coinmarketcap.com/). They have an excellent API that will allow us to get the price of the Top 100 cryptocurrencies every minute (perhaps even more frequent; however, we don't want to abuse their API). This will give us a nice tabular dataset with a time stamp and the price of a coin at the given time. We can also use exchange level data from various crypto exchanges; however, I believe CoinMarketCap will suffice. 

The next dataset that we will need is sentiment data. The best one I can think of is [Twitter's free API](https://developer.twitter.com/en/docs/tweets/search/overview) which allows a user to download the most popular tweets for a specific topic. We will be able to count the number of distinct tweets made about a particular cryptocurrency in order to capture any spikes in "voice" for a particular currency. Furthermore, there are [free Natural Language Processing sentiment packages](http://textblob.readthedocs.io/en/dev/index.html) available that can be used on each tweet to determine whether someone is saying something positive or negative about a coin. If we can gather a spike of positive sentiment, it may be a directive to take a deeper look at this coin. Additionally, there is also a possibility of using Google Trends data in order to get query volume. We may be able to see a spike in the Trend numbers correlate with the raw tweet count pulled from Twitter. 

The final (for now) dataset that we will need is news data. There are APIs for the [New York Times](https://developer.nytimes.com/) and other magazine and news sites that can be used to pull more data about coins. Google News also has an[API](https://newsapi.org/s/google-news-api) available so stories from various sites can be pulled. CNBC did a segment on their channel a few weeks ago showing users how to [buy the coin Ripple (XRP)](https://www.cnbc.com/2018/01/02/how-to-buy-ripple.html) and thus the price of Ripple skyrocketed within a few hours of that segment. Pulling this information in real time and then immediately acting on the surge of information will allow the user to react quicker than the general population. Each week there is a new partnership between a certain cryptocurrency and a Fortune 500 company or a large offshore bank. By monitoring the news sites for relevant coin information, users will be able to make informed decisions of coin price spikes or falls. Additionally, searching articles for specific words like "theft", "regulation", and "bubble" can sway the sentiment and will also play an important role on the price of a coin. [@haselton_how_2018]

#### The Outcome

Ideally, a bot will be created in order to actually perform the buying and selling in real time; however, I believe that a user can be in charge of this action. If a user is notified of a potential surge either by email or text, they will be able to act on this information and buy and sell coins on the fly. 

## Final Thoughts.

This idea is actually inspired by [Planet Money's Trump Bot](https://www.npr.org/sections/money/2017/04/07/522897876/meet-botus-planet-money-s-stock-trading-twitter-bot). The hosts of the show noticed a correlation between President Trump's tweets mentioning a certain company and that company's stock price. This idea is essentially taking that one step further by using the population as a whole in order to help guess the price of a coin. Users should take note, this is **real** investing with **real** money. There is no guarentee that this will work and the potential downside is losing the principal amount that was put in. Furthermore, while there are huge gains currently in the crypto-space, there is a large consesus that this is a bubble that is about to pop. Users should be prepared to lose everything they put in because with high reward comes high risk. [@goldmark_episode_nodate]

Furthermore, I believe that a bot is just the beginning of this idea. I truly think that we can use the data collected in order to _predict_ the cryptocurrency market. I believe that we will be able to find trends that will signify a coin's potential rise (and fall) a few hours before a spike or trough occurs. 